---
title: "EDA-Report-JALT"
subtitle: "STATX290 Statistical Practice Exploratory Data Analysis Report"
author: "Team JALT - Jerry, Aysha, Lily, and Theo"
date: today
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    embed-resources: false
    theme: cosmo
execute:
  warning: false
  message: false
  echo: true
---

# Introduction

This EDA report looks at polling data from...

The data was collected by...

`state_polls_2012.csv` and `state_polls_2016.csv` contain...

These data sets contain the variables...

An additional data set, `1976-2024-president.csv`, along with the file `codebook-us-president-1976-2020.md` is included.

# Description of Data Cleaning

- What does this data represent?
- What is measured?
- How was it collected?

*Is there any data missingness or other errors? How can this be corrected?*

- Do the measurements make sense in context? (you might need to discuss with the instructor what to do if not)

Extracting the state column
```{r}

```


# Exploratory Data Analysis

(Use summaries and visualisations to identify relationships in the data, and motivate your research questions)

*What relationships can you observe visually?*
Here, maybe include our graphs from week 3 forum?

# Research Questions

- What other data might you collect to augment this dataset? Is it available?
- Are there any ethical implications of the research questions we might ask of the data?